### ISSUE TITLE
Page

### ISSUE THREAD

**Issue by AliReza1083** [LunCoSim/lunco-site#18]
This website really look good, well done.
but you have to fix some part of it for small screen.
![image](https://user-images.githubusercontent.com/99729607/186269848-4e093356-dcd0-400f-9872-0ef449cc3ea9.png)

**Comment by TheKicker** [comment]
Thanks @AliReza1083! Fixed the overflow issue by combining the buttons into one area and removing the position:fixed on the footer.  Great stuff!
